"""empty message

Revision ID: 1160ef1aaa3
Revises: None
Create Date: 2015-12-03 15:57:40.743908

"""

# revision identifiers, used by Alembic.
revision = '1160ef1aaa3'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('label',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person',
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('login')
    )
    op.create_table('repo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('synched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('creator_login', sa.String(), nullable=False),
    sa.Column('assignee_login', sa.String(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('events_url', sa.String(), nullable=True),
    sa.Column('labels_url', sa.String(), nullable=True),
    sa.Column('comments_url', sa.String(), nullable=True),
    sa.Column('html_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignee_login'], ['person.login'], ),
    sa.ForeignKeyConstraint(['creator_login'], ['person.login'], ),
    sa.ForeignKeyConstraint(['repo_id'], ['repo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commit_id', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('event', sa.String(), nullable=True),
    sa.Column('milestone', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('issue_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['issue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('labels_issues',
    sa.Column('label_id', sa.Integer(), nullable=True),
    sa.Column('issue_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['issue.id'], ),
    sa.ForeignKeyConstraint(['label_id'], ['label.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('labels_issues')
    op.drop_table('event')
    op.drop_table('issue')
    op.drop_table('repo')
    op.drop_table('person')
    op.drop_table('label')
    ### end Alembic commands ###
